### ISSUE TITLE
bot does not turn on music

### ISSUE THREAD

**Issue by listovrik** [TheDiscorders/SelfRythm#28]
when i write !play bot joins the voice channel and exit immediately
![image](https://user-images.githubusercontent.com/61352611/109344397-53f5ef80-7877-11eb-9941-0c4d62bb9b84.png)

**Comment by Firokat** [comment]
Hi, sorry for the late reply, do you have ffmpeg installed on your machine ? Is it in the PATH ? 
It is required for the bot to run

**Comment by listovrik** [comment]
ffmpeg was not installed on the computer, which caused an error. Thanks!
