### ISSUE TITLE
Trouble with getting the bot to work.

### ISSUE THREAD

**Issue by cronchy** [TheDiscorders/SelfRythm#32]
Hi, I read through the 2 resolved issues regarding youtube search and the bot not working.

I've gone through the manual installation and i made sure to install ffmpeg and to add it to PATH. When I type a command in discord, nothing happens. No audio plays, no sign of life shows in the command prompt either.

(For example, this is something that I would type in: "$play https://youtube.com/greatsongforsureforsure"

In the screenshot below, that is pretty much all I see in the command prompt.

![image](https://user-images.githubusercontent.com/64675257/122333156-5733ea80-cefd-11eb-82d5-a11589afbdf0.png)

**Comment by Firokat** [comment]
Bot is working finz for me, please give us more details about the environnement, you can use the "Bug Report" template and fill the details. Is the bot shown as connected on Discord ?

**Comment by cronchy** [comment]
**Describe the bug**
Selfbot will not play music.

**To Reproduce**
Steps to reproduce the behavior:
$play [search]

**Expected behavior**
Play Music

**Screenshots** (Picture is pretty much all I see in the command prompt)
![image](https://user-images.githubusercontent.com/64675257/122449599-a6186900-cf6b-11eb-841a-acb954854ce6.png)

**Desktop (please complete the following information):**

OS: Windows 10
Version: 21H1
Node Version: v14.17.1

Sorry if this is too little, this is all i got.

**Comment by Firokat** [comment]
Is the bot shown as connected on Discord ? Is there an allowed.json file ? If yes, is there any Discord IDs in it ? 
When the bot gets your message, it's supposed to log it into console so it may not recieve your messages. If I remember well, it will only work if you send the command in a Discord server while being connected to a vc in the same server.
