### ISSUE TITLE
timeout for quit voice

### ISSUE THREAD

**Issue by pengengantibaju** [TheDiscorders/SelfRythm#46]
please add timeout for exit voice

**Comment by Firokat** [comment]
We provide template to be filled, not to leave the default content.

**Comment by pengengantibaju** [comment]
sorry sir

**Comment by pengengantibaju** [comment]
![image](https://user-images.githubusercontent.com/92777707/163839833-4f27c4d7-5ad1-4656-b86d-8c6625359c9c.png)
and crash report

**Comment by Firokat** [comment]
We are not working on SelfRythm anymore, but be free to make a puull request if you add this feature

**Comment by pengengantibaju** [comment]
today npm install show an eror so this is end for this repo

**Comment by Firokat** [comment]
```bash
➜  SelfRythm git:(main) npm i

added 124 packages, and audited 125 packages in 42s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
No problem for me, so check your config.

**Comment by pengengantibaju** [comment]
i use nodejs 16.. are u have discord server so i can ask you sir?

**Comment by Firokat** [comment]
I do, here it is : firokat#4278

**Comment by pengengantibaju** [comment]
![image](https://user-images.githubusercontent.com/92777707/164423001-bc9bb0ab-c7b2-41c3-bff3-ffe2d9241cbc.png)
i tried again and got stuck here

**Comment by pengengantibaju** [comment]
and now this 
root@node2141-env-5057869:~/self# npm i
npm ERR! code 1
npm ERR! path /root/self/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.4.0 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! 
npm ERR! make: Entering directory '/root/self/node_modules/better-sqlite3/build'
npm ERR!   TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR! rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! make: Leaving directory '/root/self/node_modules/better-sqlite3/build'
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=x64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/self/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/self/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! cc: fatal error: Killed signal terminated program cc1
npm ERR! compilation terminated.
npm ERR! make: *** [deps/sqlite3.target.mk:201: Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.4.0
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /root/self/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by Firokat** [comment]
It already happened to me, what is the platform / CPU architecture you are running the code on ?

**Comment by Firokat** [comment]
I do, here it is : firokat#4278

Le 21 avril 2022 03:37:08 GMT+02:00, pengengantibaju ***@***.***> a écrit :
