### ISSUE TITLE
No

### ISSUE THREAD

**Issue by GodMode13-sys** [TheDiscorders/SelfRythm#52]
**Describe the bug**
There's no Allowed.json in the folder directory.

**Expected behavior**
I expected there to be an Allowed.json so I can use discord ID's.

**Screenshots**
![image](https://user-images.githubusercontent.com/79034064/211683668-3d920c5b-55e6-4923-9cd4-6a32588b646d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Version [2H22]
 - Node v16.15.0

**Additional context**
Is there any way for me to get the file or make my own for it to work?

**Comment by Firokat** [comment]
The allowed.json file uses this structure
```json
["DISCORDID1","DISCORDID2"]
```
with DISCORDID1 and DISCORDID2 Discord IDs for allowed users.

This isn't limited to 2 users, you can add as many as you want.
