### ISSUE TITLE
make multi token support

### ISSUE THREAD

**Issue by Egra228** [TheDiscorders/SelfRythm#53]
When I throw several tokens at once, it crashes

**Comment by Egra228** [comment]
![image](https://user-images.githubusercontent.com/56909385/223157262-1ca1cf7b-e429-4def-a5e4-15205dd92c88.png)

**Comment by Egra228** [comment]
![image](https://user-images.githubusercontent.com/56909385/223161089-b688b98c-ac24-437f-bff6-2c84c8c9c864.png)

**Comment by VihaanReddyM** [comment]
it is not because there are multiple tokens the tokens are invalid....

**Comment by Luzivog** [comment]
The goal is not to cause trouble on discord servers and for personal usage you don't need multiple token support. You can run multiple instances of the program if you really need multiple music bots but we don't intend on making this scalable.

**Comment by VihaanReddyM** [comment]
Making a new instance for every token is pretty hard to do i thing cuz i tried and it did not work
