### ISSUE TITLE
failed to connect to voice channel

### ISSUE THREAD

**Issue by std-cin** [TheDiscorders/SelfRythm#54]
**Describe the bug**
The bot fails to establish a voice channel connection & throws an "VOICE_CONNECTION_TIMEOUT" exception

**To Reproduce**
1. Run the bot
2. Execute $play with any song

**Expected behavior**
The bot plays a song

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22h2
 - Node Version: 18.16.0

**Additional context**
None

**Comment by Luzivog** [comment]
Hi,

Discord v13 was posing problem, updated the entire bot using a new library for the client ([discord.js-selfbot-v13](https://www.npmjs.com/package/discord.js-selfbot-v13)) to fix the issue. Everything should be working properly now. Thank you for filling out the form.

Have fun with selfrythm!
Luzivog.
